# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14tXys7cmEAPGEilOlMSu1U2owhXjh6r1
"""

"""
16. Faça um programa para uma loja de tintas. O programa deverá pedir o tamanho
em metros quadrados da área a ser pintada. Considere que a cobertura da tinta é 
de 1 litro para cada 3 metros quadrados e que a tinta é vendida em latas de 18 
litros, que custam R$ 80,00. Informe ao usuário a quantidades de latas de tinta 
a serem compradas e o preço total.
"""

#LISTA 1 - EXERCICIO 16

area = float(input('Qual a área a ser pintada (mm2)?'))
litros = area//3
preco = litros*80
print(f'Será necessário {round(litros,2)} litros de tinta.')
print(f'O valor referente ao volume de tinta é de {round(preco,2)} reais.')