# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V7yG31nYMY9-Wm8pcJyLHBa7Pj4TIEWc
"""

# LISTA 1 - EXERCÍCIO 18

"""
18. Faça um programa que peça o tamanho de um arquivo para download (em MB) e a velocidade de um link de Internet (em
Mbps), calcule e informe o tempo aproximado de download do arquivo usando este link (em minutos).
"""

tamanho = float(input('Informe o tamanho do arquivo a ser baixado (MB):'))
velocidade = float(input('Informe a velocidade para esse download (Mbps):'))
tempo = tamanho/velocidade
minutos = tempo/60
minutos = round(minutos,2)
print(f'O download levará {minutos} minutos.')